[project]
name = "advent-of-code"
version = "1.0.0"
description = "Advent of code solutions monorepo"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.2",
    "asyncio>=4.0.0",
    "heapdict>=1.0.1",
    "python-dotenv>=1.2.1",
]
